### ISSUE TITLE
broadcasting fails

### ISSUE THREAD

**Issue by stasti** [invenia/NamedDims.jl#210] opened 2022-10-25 17:37 UTC
```julia
julia> A = NamedArray(rand(2, 1, 2))
2×1×2 Named Array{Float64, 3}

[:, :, C=1] =
A ╲ B │         1
──────┼──────────
1     │ 0.0661756
2     │  0.532365

[:, :, C=2] =
A ╲ B │        1
──────┼─────────
1     │ 0.714257
2     │ 0.924106

julia> B = NamedArray(rand(2, 2, 1))
2×2×1 Named Array{Float64, 3}

[:, :, C=1] =
A ╲ B │        1         2
──────┼───────────────────
1     │ 0.260946  0.213457
2     │ 0.785855  0.185156

julia> A .* B
ERROR: DimensionMismatch("destination axes (Base.OneTo(2), Base.OneTo(1), Base.OneTo(2)) are not compatible with source axes (Base.OneTo(2), Base.OneTo(2), Base.OneTo(2))")
Stacktrace:
 [1] throwdm(axdest::Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}, axsrc::Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}})
   @ Base.Broadcast ./broadcast.jl:1060
 [2] copyto!
   @ ./broadcast.jl:972 [inlined]
 [3] copyto!
   @ ./broadcast.jl:936 [inlined]
 [4] copy
   @ ./broadcast.jl:908 [inlined]
 [5] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{NamedArray}, Nothing, typeof(*), Tuple{NamedArray{Float64, 3, Array{Float64, 3}, Tuple{OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}}}, NamedArray{Float64, 3, Array{Float64, 3}, Tuple{OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}}}}})
   @ Base.Broadcast ./broadcast.jl:883
 [6] top-level scope
   @ REPL[292]:1
```

I submitted this issues before but I could not find it in the issue list. sorry for double-posting if it is there

**Comment by mzgubic** [comment] 2022-10-26 08:38
I am not able to reproduce this issue as it's not clear what `NamedArray` is.

However, I am able to run the following (which might be what you are looking for?)
```julia
julia> A = NamedDimsArray{(:a, :b, :c)}(rand(2, 1, 2))
2×1×2 NamedDimsArray(::Array{Float64, 3}, (:a, :b, :c)):
[:, :, c=1] =
     → b
↓ a  0.7915078188362813
     0.5377561373994327

[:, :, c=2] =
     → b
↓ a  0.31554437701506644
     0.9278437157442724

julia> B = NamedDimsArray{(:a, :b, :c)}(rand(2, 2, 1))
2×2×1 NamedDimsArray(::Array{Float64, 3}, (:a, :b, :c)):
[:, :, c=1] =
     → b
↓ a  0.816059  0.64492
     0.615956  0.846841

julia> A .* B
2×2×2 NamedDimsArray(::Array{Float64, 3}, (:a, :b, :c)):
[:, :, c=1] =
     → b
↓ a  0.645917  0.510459
     0.331234  0.455394

[:, :, c=2] =
     → b
↓ a  0.257503  0.203501
     0.571511  0.785736
```

**Comment by stasti** [comment] 2022-10-26 17:09
Dear Miha, Thank you for you response! 

It is https://github.com/davidavdav/NamedArrays.jl

julia> using NamedArrays
julia> A = NamedArray(rand(2, 1, 2))
julia> B = NamedArray(rand(2, 2, 1))
julia> A .* B
ERROR: DimensionMismatch("destination axes (Base.OneTo(2), Base.OneTo(1), Base.OneTo(2)) are not compatible with source axes (Base.OneTo(2), Base.OneTo(2), Base.OneTo(2))")
Stacktrace:
 [1] throwdm(axdest::Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}}, axsrc::Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}, Base.OneTo{Int64}})
   @ Base.Broadcast ./broadcast.jl:1060
 [2] copyto!
   @ ./broadcast.jl:972 [inlined]
 [3] copyto!
   @ ./broadcast.jl:936 [inlined]
 [4] copy
   @ ./broadcast.jl:908 [inlined]
 [5] materialize(bc::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{NamedArray}, Nothing, typeof(*), Tuple{NamedArray{Float64, 3, Array{Float64, 3}, Tuple{OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}}}, NamedArray{Float64, 3, Array{Float64, 3}, Tuple{OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}, OrderedCollections.OrderedDict{String, Int64}}}}})
   @ Base.Broadcast ./broadcast.jl:883
 [6] top-level scope
   @ REPL[292]:1

**Comment by stasti** [comment] 2022-10-26 17:18
oh.. I see I ask in a wrong place. "NamedArray" <--> "NamedDimsArray". sorry about that. I will try your suggestions. Thanks!

**Comment by mzgubic** [comment] 2022-10-26 17:29
No worries, I will close the issue as it is not related to the package. If you find issues with NamedDims please feel encouraged to open an issue though.

**Closed by mzgubic** 2022-10-26 17:29 UTC

**Comment by stasti** [comment] 2022-10-27 17:18
thanks! there is an issue with the dimension names after broadcasting. I will post it as a separate issue.
